import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../componentes/Menu'
import Layout from '../componentes/Layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tienda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout>
      <h1>Inicio</h1>
      <hr />
     </Layout>
     </div>

  )
  
}
